name: Publish Docker Latest
on:
  release:
    types: [published, created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build -t goatcommunity/database:${GITHUB_REF} .
    - name: Login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish
      run: docker push goatcommunity/database:${GITHUB_REF}