name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: docker build -t masterkorp/docker-postgis-12:latest .
    - name: Login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish
      run: docker publish masterkorp/docker-postgis-12:latest